name: kisgeri24
description: Kisgeri24 Climbing Competition Application
version: 1.0.0+1
publish_to: "none"
environment:
  sdk: "3.12.1"

dependencies:
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.2

  auto_size_text: ^3.0.0

  custom_sliding_segmented_control: ^1.8.5

  email_validator: ^3.0.0

  logger: ^2.7.0

  shared_preferences: ^2.5.5
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^7.1.7
  http: ^1.6.0
  image_picker: ^1.2.2
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^2.0.1
  the_apple_sign_in: ^1.1.1
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.2
  file_picker: ^11.0.2

  flutter:
    sdk: flutter
  background_fetch: ^1.7.0
  equatable: ^2.0.8
  timer_count_down: ^2.2.2
  responsive_sizer: ^3.3.1

  cupertino_icons: ^1.0.9
  firebase_database: ^12.4.2

  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.20.2
  numberpicker: ^2.1.2
  expandable_menu: ^0.0.5
  popup_menu: ^2.1.0
  pie_menu: ^3.7.0
  star_menu: ^4.0.1
  flutter_local_notifications: ^22.0.0

dev_dependencies:
  build_runner: ^2.15.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  lint: ^2.8.0
  mockito: ^5.6.4

flutter_launcher_icons:
  android: "ic_launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher_round"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ic_launcher_round"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher_round"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ic_launcher_round"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher_round.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
