// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR_t9WU8ADjyVoJpgCAqvEi-3-JSOt-0U',
    appId: '1:661526883314:web:c72a724217a4999a4bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    authDomain: 'kisgeri24-4d598.firebaseapp.com',
    databaseURL:
        'https://kisgeri24-4d598-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisgeri24-4d598.appspot.com',
    measurementId: 'G-PHXG0FBWEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCsJKXsTQ9mPKkXOM6WdCoxUerblk3ooc',
    appId: '1:661526883314:android:4453b2e55edb94974bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    databaseURL:
        'https://kisgeri24-4d598-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisgeri24-4d598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4VOZGgvGBXPpPFnkf1edyAfkcx7hMGNA',
    appId: '1:661526883314:ios:e1ee42bce6b349334bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    databaseURL:
        'https://kisgeri24-4d598-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisgeri24-4d598.appspot.com',
    iosClientId:
        '661526883314-1qhavrgp9sbjr7n57jrq4dmeqqo141kg.apps.googleusercontent.com',
    iosBundleId: 'com.kisgeri24.flutterkisgeri24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4VOZGgvGBXPpPFnkf1edyAfkcx7hMGNA',
    appId: '1:661526883314:ios:e6bbde8ec4b5e4d24bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    databaseURL:
        'https://kisgeri24-4d598-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisgeri24-4d598.appspot.com',
    iosClientId:
        '661526883314-beu7v1ejtu6rqcvje09n77ve366cp0kd.apps.googleusercontent.com',
    iosBundleId: 'com.kisgeri24.flutterkisgeri24.mac',
  );
}
