// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR_t9WU8ADjyVoJpgCAqvEi-3-JSOt-0U',
    appId: '1:661526883314:web:bb597e61dcf3e5684bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    authDomain: 'kisgeri24-4d598.firebaseapp.com',
    storageBucket: 'kisgeri24-4d598.appspot.com',
    measurementId: 'G-DZHJF5RNR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCsJKXsTQ9mPKkXOM6WdCoxUerblk3ooc',
    appId: '1:661526883314:android:429850e88d5c10a24bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    storageBucket: 'kisgeri24-4d598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4VOZGgvGBXPpPFnkf1edyAfkcx7hMGNA',
    appId: '1:661526883314:ios:2ab62fcd86b887c44bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    storageBucket: 'kisgeri24-4d598.appspot.com',
    iosClientId: '661526883314-ptaf3oqjf0ppc6cpinv8tviu8alophqs.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4VOZGgvGBXPpPFnkf1edyAfkcx7hMGNA',
    appId: '1:661526883314:ios:0598734a8c78c5ff4bd96b',
    messagingSenderId: '661526883314',
    projectId: 'kisgeri24-4d598',
    storageBucket: 'kisgeri24-4d598.appspot.com',
    iosClientId: '661526883314-d4uildhr48a04qieghpdu0gcatd1f80a.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen.mac',
  );
}
